services:
  app:
    build: .
    container_name: monitoramento-espacial-app 
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      # --- Conexão Neon (Nuvem) ---
      # Garante que o Docker use estas credenciais, ignorando o local
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ep-tiny-dust-adys1axb-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require"
      SPRING_DATASOURCE_USERNAME: "neondb_owner"
      SPRING_DATASOURCE_PASSWORD: "npg_WhI5DaSvtXo1"
      # Configurações do JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"

# Não precisamos mais de volumes locais pois o banco está na nuvem