services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/appdb"
      SPRING_DATASOURCE_USERNAME: "app"
      SPRING_DATASOURCE_PASSWORD: "app"
      # opcional: mostrar SQL no log
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: spring-db
    environment:
      POSTGRES_DB: "appdb"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
